<a href="https://colab.research.google.com/github/KeerthiVasan-ai/deep-learning-tools-lab/blob/main/2_Data_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

import os
import pathlib

## Dataset from List

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices(
    [1,2,3]
)
for element in dataset:
  print(element)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
dataset = tf.data.Dataset.from_tensors(
    [1,2,3]
)
for element in dataset:
  print(element)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


### Dataset from TextFile

In [ ]:
directory_url = "https://storage.googleapis.com/download.tensorflow.org/data/illiad/"
file_names = ['cowper.txt','derby.txt','butler.txt']

file_paths = [
    tf.keras.utils.get_file(file_name,directory_url+file_name)
    for file_name in file_names
]

807992/807992 [==============================] - 0s 0us/step


In [ ]:
text_line_dataset = tf.data.TextLineDataset(file_paths)

for line in text_line_dataset.take(5):
  print(line.numpy())

b"\xef\xbb\xbfAchilles sing, O Goddess! Peleus' son;"
b'His wrath pernicious, who ten thousand woes'
b"Caused to Achaia's host, sent many a soul"
b'Illustrious into Ades premature,'
b'And Heroes gave (so stood the will of Jove)'


### Dataset from set of Files

In [ ]:
flower_root = (
    tf.keras.utils.get_file(
        "flower_photos",
        "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz",
        untar = True
    )
)
flower_root = pathlib.Path(flower_root)

228813984/228813984 [==============================] - 2s 0us/step


In [ ]:
file_path_ds = tf.data.Dataset.list_files(str(flower_root/'*/*'))

def process_path(file_path):
  label = tf.strings.split(file_path,os.sep)[-2]
  return tf.io.read_file(file_path),label

In [ ]:
labeled_data = file_path_ds.map(process_path)

In [ ]:
for image,label in labeled_data.take(1):
  print(image,label,sep="\n")
  plt.show(image)


tf.Tensor(b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00H\x00H\x00\x00\xff\xe2\x02@ICC_PROFILE\x00\x01\x01\x00\x00\x020ADBE\x02\x10\x00\x00mntrRGB XYZ \x07\xcf\x00\x06\x00\x03\x00\x00\x00\x00\x00\x00acspAPPL\x00\x00\x00\x00none\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf6\xd6\x00\x01\x00\x00\x00\x00\xd3-ADBE\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\ncprt\x00\x00\x00\xfc\x00\x00\x002desc\x00\x00\x010\x00\x00\x00kwtpt\x00\x00\x01\x9c\x00\x00\x00\x14bkpt\x00\x00\x01\xb0\x00\x00\x00\x14rTRC\x00\x00\x01\xc4\x00\x00\x00\x0egTRC\x00\x00\x01\xd4\x00\x00\x00\x0ebTRC\x00\x00\x01\xe4\x00\x00\x00\x0erXYZ\x00\x00\x01\xf4\x00\x00\x00\x14gXYZ\x00\x00\x02\x08\x00\x00\x00\x14bXYZ\x00\x00\x02\x1c\x00\x00\x00\x14text\x00\x00\x00\x00Copyright 1999 Adobe Systems Incorporated\x00\x00\x00desc\x00\x00\x00\x00\x00\x00\x00\x11Adobe 

### Batching Dataset

In [ ]:
dataset = tf.data.Dataset.range(100)
batched_dataset = dataset.batch(15)

for element in batched_dataset:
  print(element)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14], shape=(15,), dtype=int64)
tf.Tensor([15 16 17 18 19 20 21 22 23 24 25 26 27 28 29], shape=(15,), dtype=int64)
tf.Tensor([30 31 32 33 34 35 36 37 38 39 40 41 42 43 44], shape=(15,), dtype=int64)
tf.Tensor([45 46 47 48 49 50 51 52 53 54 55 56 57 58 59], shape=(15,), dtype=int64)
tf.Tensor([60 61 62 63 64 65 66 67 68 69 70 71 72 73 74], shape=(15,), dtype=int64)
tf.Tensor([75 76 77 78 79 80 81 82 83 84 85 86 87 88 89], shape=(15,), dtype=int64)
tf.Tensor([90 91 92 93 94 95 96 97 98 99], shape=(10,), dtype=int64)


### Shuffling Dataset

In [ ]:
dataset = tf.data.Dataset.range(20)
shuffled_dataset = dataset.shuffle(3,reshuffle_each_iteration=False)

for element in shuffled_dataset:
  print(element)

tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(11, shape=(), dtype=int64)
tf.Tensor(10, shape=(), dtype=int64)
tf.Tensor(13, shape=(), dtype=int64)
tf.Tensor(14, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(12, shape=(), dtype=int64)
tf.Tensor(16, shape=(), dtype=int64)
tf.Tensor(17, shape=(), dtype=int64)
tf.Tensor(19, shape=(), dtype=int64)
tf.Tensor(18, shape=(), dtype=int64)
tf.Tensor(15, shape=(), dtype=int64)


### Building a Pipeline

#### Data Source

In [ ]:
train_ds,test_ds= tf.keras.datasets.fashion_mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step


In [ ]:
def normalize_image(img,label):
  return (tf.cast(img,tf.float32) / 255.0, label)

#### Train Data Pipeline

In [ ]:
train_dataset = tf.data.Dataset.from_tensor_slices(train_ds)

train_dataset = train_dataset.map(
    normalize_image,num_parallel_calls=tf.data.AUTOTUNE
)

train_dataset = train_dataset.cache()
train_dataset = train_dataset.shuffle(len(train_dataset))

train_dataset = train_dataset.batch(64)
train_dataset = train_dataset.prefetch(tf.data.AUTOTUNE)

train_dataset


<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.uint8, name=None))>

#### Test Data Pipeline

In [ ]:
test_dataset = tf.data.Dataset.from_tensor_slices(test_ds)

test_dataset = test_dataset.map(
    normalize_image,num_parallel_calls=tf.data.AUTOTUNE
)

test_dataset = test_dataset.cache()
test_dataset = test_dataset.shuffle(len(train_dataset))

test_dataset = test_dataset.batch(64)
test_dataset = test_dataset.prefetch(tf.data.AUTOTUNE)

test_dataset

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.uint8, name=None))>

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers

model = Sequential([
    layers.InputLayer(input_shape=(28,28)),
    layers.Reshape((28,28,1)),
    layers.Conv2D(8,3,activation="relu"),
    layers.Conv2D(8,3,activation="relu"),
    layers.Conv2D(8,3,activation="relu"),
    layers.GlobalAveragePooling2D(),
    layers.Flatten(),
    layers.Dense(32,activation="relu"),
    layers.Dense(10,activation="softmax"),
])

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape_2 (Reshape)         (None, 28, 28, 1)         0         
                                                                 
 conv2d_6 (Conv2D)           (None, 26, 26, 8)         80        
                                                                 
 conv2d_7 (Conv2D)           (None, 24, 24, 8)         584       
                                                                 
 conv2d_8 (Conv2D)           (None, 22, 22, 8)         584       
                                                                 
 global_average_pooling2d_2  (None, 8)                 0         
  (GlobalAveragePooling2D)                                       
                                                                 
 flatten (Flatten)           (None, 8)                 0         
                                                      

In [ ]:
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer = "adam",
    metrics=["accuracy"]
)

In [ ]:
model.fit(train_dataset,epochs=2,validation_data=test_dataset)

Epoch 1/2
938/938 [==============================] - 38s 39ms/step - loss: 1.2902 - accuracy: 0.5057 - val_loss: 1.0095 - val_accuracy: 0.6089
Epoch 2/2
938/938 [==============================] - 37s 40ms/step - loss: 0.9560 - accuracy: 0.6365 - val_loss: 0.9328 - val_accuracy: 0.6464


In [ ]:
loss,accuracy = model.evaluate(test_dataset)

157/157 [==============================] - 2s 10ms/step - loss: 0.8890 - accuracy: 0.6703
